---
- name: logstash.conf
  template:
    src: logstash.conf.j2
    dest: ./logstash_dir/logstash.conf
    owner: root
    group: root
    mode: 0644

- name: logstash.yaml
  template:
    src: logstash.yaml.j2
    dest: ./logstash_dir/logstash.yaml
    owner: root
    group: root
    mode: 0644

- name: Create an "{{ docker_image_logstash }}" container
  community.docker.docker_container:
    name: "{{ docker_container_name_logstash }}"
    image: "{{ docker_image_logstash }}"
    user: root
    env:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"   
      ELASTICSEARCH_HOSTS: "http://{{ docker_container_name_elasticsearch }}:{{ docker_container_elasticsearch_port }}"
    ports:
      - "9600:9600"
      - "5044:5044"
      - "5400:5400"
    networks:
      - name: "{{ docker_network_name }}"
    volumes:
        - ./container_dirs/logstash_dir/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
        - ./container_dirs/logstash_dir/logstash.yaml:/usr/share/logstash/config/logstash.yml:ro 
        - ./logs_file/logs_file_logstash:/usr/share/logstash/logs
