---
- name: Create an logstash:7.7.0 container
  community.docker.docker_container:
    name: logstash770
    image: studentnv/logstash:7.7.0
    env:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"   
    ports:
      - "9600:9600"
      - "5044:5044"
    networks:
      - name: elastic