---
- name: logstash.conf
  template:
    src: logstash.conf.j2
    dest: ./logstash_dir/logstash.conf
    owner: root
    group: root
    mode: 0644

- name: logstash.yaml
  template:
    src: logstash.yaml.j2
    dest: ./logstash_dir/logstash.yaml
    owner: root
    group: root
    mode: 0644

- name: Create an logstash:7.7.0 container
  community.docker.docker_container:
    name: "{{ docker_container_name_logstash }}"
    image: studentnv/logstash:7.7.0
    env:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"   
      ELASTICSEARCH_HOSTS: "http://{{ docker_container_name_elasticsearch }}:{{ docker_container_elasticsearch_port }}"
    ports:
      - "9600:9600"
      - "5044:5044"
      - "5400:5400"
    networks:
      - name: "{{ docker_network_name }}"
    volumes:
        - ./logstash_dir/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
        - ./logstash_data:/usr/share/logstash/logstash_data
        - ./logstash_dir/logstash.yaml:/usr/share/logstash/config/logstash.yml:ro 
        - ./logs/file:/usr/share/logstash/logstash-output.log:rw
