filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            contains:
              docker.container.image: "studentnv/filebeat:7.7.0"
          config:
            - type: container
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
filebeat.inputs:
- type: log
  paths:
    - "/usr/share/filebeat/test.log"


output.logstash:
  hosts: ["logstash770:5400"]

