---
docker_container_name_elasticsearch: elasticsearch770
docker_container_name_filebeat_to_file: filebeat_file770
docker_container_name_filebeat_to_logstash: filebeat_logstash770
docker_container_name_logstash: logstash770
docker_container_name_kibana: kibana770