---
- name: Create an elasticsearch:7.7.0 container
  community.docker.docker_container:
    name: "{{ docker_container_name_elasticsearch }}"
    image: studentnv/elasticsearch:7.7.0
    env:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    ports:
      - "9300:9300"
      - "9200:9200"
    networks:
      - name: elastic