---
- name: POST import kibana dashboard
  ansible.builtin.uri:
    url: "http://{{ ansible_host }}:{{ docker_container_kibana_port }}/api/kibana/dashboards/import"
    method: POST
    body_format: json
    headers:
      Content-Type: application/json
      kbn-xsrf: true
    src: "{{ path_with_kibana_dashboard_json }}"
