---
- name: Create an filebeat:7.7.0 container
  community.docker.docker_container:
    name: "{{ docker_container_name_filebeat_to_file }}"
    image: studentnv/filebeat:7.7.0
    env:
      setup.kibana.host: "kibana770:5601"
      #output.elasticsearch.hosts: "[\"elasticsearch770:9200\"]"
    output_logs: true
    log_driver: json-file
    networks:
      - name: elastic
    user: root
    volumes:
      - ./filebeat_dir_to_file/filebeat.docker.yaml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: true
