---
- name: Create an filebeat:7.7.0 container
  community.docker.docker_container:
    name: "{{ docker_container_name_filebeat }}"
    image: studentnv/filebeat:7.7.0
    env:
      setup.kibana.host: "kibana770:5601"
      output.elasticsearch.hosts: "[\"elasticsearch7709200\"]"
    output_logs: true
    log_driver: json-file
    networks:
      - name: elastic