---
- name: Set filebeat container name to logstash
  set_fact:
    var_filebeat_container_name: "{{ docker_container_name_filebeat_to_logstash }}"
   
- name: filebeat.docker.yml to logstash
  template:
    src: filebeat.docker.yml.j2
    dest: "{{ path_with_filebeat_to_logstash_docker_yml }}"
    owner: "{{ user_for_docker_container_filebeat }}"
    group: "{{ user_for_docker_container_filebeat }}"
    mode: "{{ folder_permissions_filebeat }}"

- name: Create an "{{ docker_image_filebeat }}" container to logstash
  community.docker.docker_container:
    name: "{{ docker_container_name_filebeat_to_logstash }}"
    image: "{{ docker_image_filebeat }}" 
    env:
      setup.kibana.host: "{{ docker_container_name_kibana }}:{{ docker_container_kibana_port }}"
    networks:
      - name: "{{ docker_network_name }}"
    user: "{{ user_for_docker_container_filebeat }}"
    volumes:
      - "{{ path_with_filebeat_to_logstash_docker_yml }}:/usr/share/filebeat/filebeat.yml:ro"
      - "{{ path_with_test_log }}:/usr/share/filebeat/test.log:ro"
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

- name: Set filebeat container name to file
  set_fact:
    var_filebeat_container_name: "{{ docker_container_name_filebeat_to_file }}"

- name: filebeat.docker.yml to file  
  template:
    src: filebeat.docker.yml.j2
    dest: ./container_dirs/filebeat_dir/filebeat_to_file.docker.yml
    owner: "{{ user_for_docker_container_filebeat }}"
    group: "{{ user_for_docker_container_filebeat }}"
    mode: "{{ folder_permissions_filebeat }}"

- name: Create an "{{ docker_image_filebeat }}" container to file 
  community.docker.docker_container:
    name: "{{ docker_container_name_filebeat_to_file }}"
    image: "{{ docker_image_filebeat }}" 
    env:
      setup.kibana.host: "kibana770:5601"
    networks:
      - name: "{{ docker_network_name }}"
    user: "{{ user_for_docker_container_filebeat }}"
    volumes:
      - ./container_dirs/filebeat_dir/filebeat_to_file.docker.yml:/usr/share/filebeat/filebeat.yml:ro
      - "{{ path_with_test_log }}:/usr/share/filebeat/test.log:ro"
      - "{{ path_with_logs_file_filebeat }}:/usr/share/filebeat/logs"
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
