---
- name: Set filebeat container name to logstash
  set_fact:
    var_filebeat_container_name: filebeat_logstash770

- name: Print return information from the previous task
  ansible.builtin.debug:
    var: var_filebeat_container_name
    
- name: filebeat.docker.yaml to logstash
  template:
    src: filebeat.docker.yaml.j2
    dest: ./filebeat_dir_to_logstash/filebeat.docker.yaml
    owner: root
    group: root
    mode: 0644

- name: Create an filebeat:7.7.0 container to logstash
  community.docker.docker_container:
    name: "{{ docker_container_name_filebeat_to_logstash }}"
    image: studentnv/filebeat:7.7.0
    env:
      setup.kibana.host: "kibana770:5601"
      #output.elasticsearch.hosts: "[\"elasticsearch770:9200\"]"
    output_logs: true
    log_driver: json-file
    networks:
      - name: elastic
    user: root
    volumes:
      - ./docker_logs.log:/usr/share/filebeat/docker_logs.log:ro
      - ./filebeat_dir_to_logstash/filebeat.docker.yaml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: true


- name: Set filebeat container name to file
  set_fact:
    var_filebeat_container_name: "{{ docker_container_name_filebeat_to_file }}"

- name: filebeat.docker.yaml to file  
  template:
    src: filebeat.docker.yaml.j2
    dest: ./filebeat_dir_to_file/filebeat.docker.yaml
    owner: root
    group: root
    mode: 0644

- name: Create an filebeat:7.7.0 container to file 
  community.docker.docker_container:
    name: "{{ docker_container_name_filebeat_to_file }}"
    image: studentnv/filebeat:7.7.0
    env:
      setup.kibana.host: "kibana770:5601"
      #output.elasticsearch.hosts: "[\"elasticsearch770:9200\"]"
    output_logs: true
    log_driver: json-file
    networks:
      - name: elastic
    user: root
    volumes:
      - ./filebeat_dir_to_file/filebeat.docker.yaml:/usr/share/filebeat/filebeat.yml:ro
      - ./test.log:/usr/share/filebeat/test.log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./logs_file:/usr/share/filebeat/logs
    restart: true



