---
- name: Set filebeat container name to logstash
  set_fact:
    var_filebeat_container_name: "{{ docker_container_name_filebeat_to_logstash }}"
   
- name: filebeat.docker.yaml to logstash
  template:
    src: filebeat.docker.yaml.j2
    dest: ./filebeat_dir/filebeat_to_logstash.docker.yaml
    owner: root
    group: root
    mode: 0644

- name: Create an filebeat:7.7.0 container to logstash
  community.docker.docker_container:
    name: "{{ docker_container_name_filebeat_to_logstash }}"
    image: "{{ docker_image_filebeat }}" 
    env:
      setup.kibana.host: "{{ docker_container_name_kibana }}:5601"
      #output.elasticsearch.hosts: "[\"elasticsearch770:9200\"]"
    output_logs: true
    log_driver: json-file
    networks:
      - name: "{{ docker_network_name }}"
    user: root
    volumes:
      - ./filebeat_dir/filebeat_to_logstash.docker.yaml:/usr/share/filebeat/filebeat.yml:ro
      - ./test.log:/usr/share/filebeat/test.log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: true


- name: Set filebeat container name to file
  set_fact:
    var_filebeat_container_name: "{{ docker_container_name_filebeat_to_file }}"

- name: filebeat.docker.yaml to file  
  template:
    src: filebeat.docker.yaml.j2
    dest: ./filebeat_dir/filebeat_to_file.docker.yaml
    owner: root
    group: root
    mode: 0644

- name: Create an filebeat:7.7.0 container to file 
  community.docker.docker_container:
    name: "{{ docker_container_name_filebeat_to_file }}"
    image: "{{ docker_image_filebeat }}" 
    env:
      setup.kibana.host: "kibana770:5601"
      #output.elasticsearch.hosts: "[\"elasticsearch770:9200\"]"
    output_logs: true
    log_driver: json-file
    networks:
      - name: "{{ docker_network_name }}"
    user: root
    volumes:
      - ./filebeat_dir/filebeat_to_file.docker.yaml:/usr/share/filebeat/filebeat.yml:ro
      - ./test.log:/usr/share/filebeat/test.log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./logs_file_filebeat:/usr/share/filebeat/logs
    restart: true



