---
- name: Create an "{{ docker_image_kibana }}" container
  community.docker.docker_container:
    name: "{{ docker_container_name_kibana }}"
    image: "{{ docker_image_kibana }}"
    ports:
      - "{{ docker_container_kibana_port }}:5601"
    env:
      ELASTICSEARCH_HOSTS: "http://{{ docker_container_name_elasticsearch }}:{{ docker_container_elasticsearch_port }}"
    networks:
      - name: "{{ docker_network_name }}"

- name: Check that a page kibana returns successfully 
  ansible.builtin.uri:
    url: http://{{ ansible_host }}:{{ docker_container_kibana_port }}/api/status
    method: GET
  register: _result
  until: _result.status == 200 and _result.json.status.overall.state == 'green'
  retries: 60
  delay: 10

- name: POST import kibana v7.7.0 dashboard
  ansible.builtin.uri:
    url: "http://{{ ansible_host }}:{{ docker_container_kibana_port }}/api/kibana/dashboards/import"
    method: POST
    body_format: json
    headers:
      Content-Type: application/json
      kbn-xsrf: true
    src: "{{ path_with_kibana_dashboard_json_v770 }}"
  when: docker_image_version == "7.7.0"

- name: POST import kibana v6.7.2 dashboard
  ansible.builtin.uri:
    url: "http://{{ ansible_host }}:{{ docker_container_kibana_port }}/api/kibana/dashboards/import"
    method: POST
    body_format: json
    headers:
      Content-Type: application/json
      kbn-xsrf: true
    src: "{{ path_with_kibana_dashboard_json_v672 }}"
  when: docker_image_version == "6.7.2"
