---
- name: Create an kibana:7.7.0 container
  community.docker.docker_container:
    name: "{{ docker_container_name_kibana }}"
    image: studentnv/kibana:7.7.0
    #restart: true
    ports:
      - "5601:5601"
    env:
      ELASTICSEARCH_HOSTS: "http://{{ docker_container_name_elasticsearch }}:9200"
    networks:
      - name: elastic
