---
- name: Create an "{{ docker_image_kibana }}" container
  community.docker.docker_container:
    name: "{{ docker_container_name_kibana }}"
    image: "{{ docker_image_kibana }}"
    ports:
      - "5601:5601"
    env:
      ELASTICSEARCH_HOSTS: "http://{{ docker_container_name_elasticsearch }}:{{ docker_container_elasticsearch_port }}"
    networks:
      - name: "{{ docker_network_name }}"
